### ISSUE TITLE
Flathub version out of date

### ISSUE THREAD

**Issue by mcoghill100** [azagaya/laigter#105]
Hey, I was wondering if there were any plans to release the latest version of flathub? Looks like that version is reporting as 1.10.7

https://flathub.org/apps/io.itch.azagaya.Laigter

**Comment by azagaya** [comment]
That image was not maintained by me, and i know almost nothing about flathub or flatpacks sadly. So it is not in my plans to update it, at least on my own. If someone helps me with this i would appreciate it though.

**Comment by mcoghill100** [comment]
Hey @azagaya 

I did some digging and was able to build the newest version and launch it using flatpak. It looks like the manifest for the previous version was stored here:

https://github.com/flathub/io.itch.azagaya.Laigter

So I copied the .yaml and .patch file and ran the following commands to test the build/run locally

get URL for release https://github.com/azagaya/laigter/archive/refs/tags/1.11.0.tar.gz
download .tar.gz and run "shasum -a 256 laigter-1.11.0.tar.gz" to get the sha-256 entry
sudo dnf install flatpak flatpak-builder 
flatpak install flathub org.kde.platform//5.15-21.08 org.kde.Sdk//5.15-21.08
created an empty directory to place the .yaml and .patch file
update the .yaml and .patch file to reflect the newer version (see below)
created a "test_build" folder in the empty directory
followed the following tutorial on how to build it: https://docs.flatpak.org/en/latest/first-build.html -

ran "flatpak-builder test_build io.itch.azagaya.Laigter.yaml --force-clean"
It compiled successfully so I created a "repo" folder in the originally directory ran "flatpak-builder --repo=repo --force-clean test_build io.itch.azagaya.Laigter.yaml"
added that repo to flatpak "flatpak --user remote-add --no-gpg-verify tutorial-repo repo"
installed the app from that repo "flatpak --user install tutorial-repo io.itch.azagaya.Laigter.yaml"
then launched the app via flatpak "flatpak run io.itch.azagaya.Laigter"


![image](https://github.com/azagaya/laigter/assets/10782112/6957b8da-2eed-486f-9ad2-21dc1850352e)

updated .yaml file:
```
app-id: io.itch.azagaya.Laigter
runtime: org.kde.Platform
runtime-version: "5.15-21.08"
sdk: org.kde.Sdk
command: laigter
rename-icon: laigter
rename-desktop-file: laigter.desktop
rename-appdata-file: laigter.appdata.xml

finish-args:
  - --share=ipc
  - --share=network
  - --socket=x11
  - --filesystem=home
  - --device=dri

modules:
  - name: laigter
    buildsystem: qmake

    sources:
      - type: archive
        url: https://github.com/azagaya/laigter/archive/refs/tags/1.11.0.tar.gz
        sha256: 77823b770f099843e1c0f6408156367c3f12b22dc897781aebe079c8a67c62e4
      - type: patch
        path: appdata-fixes.patch

    post-install:
      - sed -i 's/<icon name="laigter"/<icon name="$FLATPAK_ID"/' dist/x-laigter-project.xml
      - install -Dm644 dist/x-laigter-project.xml /app/share/mime/packages/$FLATPAK_ID.xml
 ```

Updated .patch file
```
--- laigter-1.11.0/dist/laigter.appdata.xml-orig	2022-02-06 16:53:08.756065009 -0500
+++ laigter-1.11.0/dist/laigter.appdata.xml	2022-02-06 17:47:27.122850012 -0500
@@ -1,12 +1,12 @@
 <?xml version="1.0" encoding="UTF-8"?>
 <!-- Copyright 2019 Pablo Ivan Fonovich <azagaya.games@gmail.com> -->
 <component type="desktop">
-  <id>laigter</id>
+  <id>io.itch.azagaya.Laigter</id>
   <metadata_license>CC0-1.0</metadata_license>
   <project_license>GPL-3.0+</project_license>
   <name>Laigter</name>
   <summary>Tool to generate normal, specular, occlussion and parallax maps for 2D textures</summary>
-  ​<launchable type="desktop-id">laigter</launchable>
+  ​<launchable type="desktop-id">laigter.desktop</launchable>
   <description>
     <p>
       Laigter is a tool that automatically generates maps for dynamic lighting effects
@@ -29,4 +29,18 @@
   <url type="donation">https://www.patreon.com/azagaya</url>
   <developer_name>Pablo Ivan Fonovich</developer_name>
   <update_contact>azagaya.games@gmail.com</update_contact>
+   <releases>
+    <release version="1.11.0" date="2023-08-15" />
+    <release version="1.10.7" date="2021-10-18" />
+    <release version="1.10.1" date="2020-07-26" />
+    <release version="1.10" date="2020-07-05" />
+    <release version="1.9.2" date="2020-05-30" />
+    <release version="1.9.1" date="2020-05-10" />
+    <release version="1.9" date="2020-04-16" />
+    <release version="1.8.1" date="2020-02-08" />
+    <release version="1.8" date="2019-12-09" />
+    <release version="1.7" date="2019-10-05" />
+    <release version="1.6" date="2019-09-04" />
+  </releases>
+  <content_rating type="oars-1.1" />
 </component>

```

and based on reading this page https://docs.flathub.org/docs/for-app-authors/maintenance I think updating the .yaml and .patch files in the original repo I linked will have flathub will automatically push out the updates. However when I launched this flatpak Laigter version I noticed that it respected my dark theme in Gnome which the appimage did not:

Appimage with dark theme enabled:
![image](https://github.com/azagaya/laigter/assets/10782112/7e610890-3532-4e0d-a9c8-4010922b9455)

Flatpak with dark theme enabled:
![image](https://github.com/azagaya/laigter/assets/10782112/e5e19835-7cd3-4112-8e15-2e4095168628)

Not sure if this is a make option or a difference in the KDE/QT version used.

**Comment by mcoghill100** [comment]
I was able to update the SDK to 5.15.-23.08 and it was able to launch:

flatpak install flathub org.kde.platform//5.15-23.08 org.kde.Sdk//5.15-23.08

```
app-id: io.itch.azagaya.Laigter
runtime: org.kde.Platform
runtime-version: "5.15-23.08"
sdk: org.kde.Sdk
command: laigter
rename-icon: laigter
rename-desktop-file: laigter.desktop
rename-appdata-file: laigter.appdata.xml

finish-args:
  - --share=ipc
  - --share=network
  - --socket=x11
  - --filesystem=home
  - --device=dri

modules:
  - name: laigter
    buildsystem: qmake

    sources:
      - type: archive
        url: https://github.com/azagaya/laigter/archive/refs/tags/1.11.0.tar.gz
        sha256: 77823b770f099843e1c0f6408156367c3f12b22dc897781aebe079c8a67c62e4
      - type: patch
        path: appdata-fixes.patch

    post-install:
      - sed -i 's/<icon name="laigter"/<icon name="$FLATPAK_ID"/' dist/x-laigter-project.xml
      - install -Dm644 dist/x-laigter-project.xml /app/share/mime/packages/$FLATPAK_ID.xml
 ```

It doesn't seem to like anything 6.x though
